List<List<dynamic>> categoriesAndFilesList = [
  [
    'Actors',
    'assets/actors.json',
    '20',
    'assets/images/actors/Angela Bassett.png',
  ],
  [
    'Animals',
    'assets/animals.json',
    '20',
    'assets/images/animals/Bear.png',
  ],
  [
    'Car Logos',
    'assets/cars.json',
    '20',
    'assets/images/cars/Alfa Romeo.png',
  ],
  [
    'Disney Characters',
    'assets/disney_characters.json',
    '20',
    'assets/images/disney_characters/Bambi.png',
  ],
  [
    'Country Flags',
    'assets/country_flags.json',
    '20',
    'assets/images/country_flags/Albania.png',
  ],
  [
    'Fashion Brands',
    'assets/fashion_brands.json',
    '20',
    'assets/images/fashion_brands/Adidas.png',
  ],
  [
    'Food Chain',
    'assets/food_chain.json',
    '20',
    'assets/images/food_chain/Applebees.png',
  ],
  [
    'Flowers',
    'assets/flowers.json',
    '20',
    'assets/images/flowers/Carnation.png',
  ],
  [
    'Mobile Games',
    'assets/mobile_games.json',
    '20',
    'assets/images/mobile_games/Ballz.png',
  ],
  //!TODO Animal - Q&A
  // [
  //   'Animal - Q&A',
  //   'assets/animal-QandA.json',
  //   '20',
  //   'assets/images/animal-QandA/xxx.png'),
  // ],
  [
    'Animated Movies',
    'assets/animated_movies.json',
    '20',
    'assets/images/animated_movies/Akira.png',
  ],
  [
    'DJs',
    'assets/djs.json',
    '20',
    'assets/images/djs/Avicii.png',
  ],
  [
    'Fashion Brands',
    'assets/fashion_brands.json',
    '20',
    'assets/images/fashion_brands/Adidas.png',
  ],
  [
    'Sportspersons',
    'assets/sportspersons.json',
    '20',
    'assets/images/sportspersons/Pele.png',
  ],
  [
    'Fruits',
    'assets/fruits.json',
    '20',
    'assets/images/fruits/Apple.png',
  ],
  [
    'Sea Creatures',
    'assets/sea_creatures.json',
    '20',
    'assets/images/sea_creatures/Angelfish.png',
  ],
  [
    'Singers',
    'assets/singers.json',
    '20',
    'assets/images/singers/Amy Winehouse.png',
  ],
  [
    'Social Media',
    'assets/social_media.json',
    '20',
    'assets/images/social_media/Instagram.png',
  ],
  [
    'Animated Series',
    'assets/animated_series.json',
    '20',
    'assets/images/animated_series/Aladdin.png',
  ],
  [
    'Fashion Brands',
    'assets/fashion_brands.json',
    '20',
    'assets/images/fashion_brands/Adidas.png',
  ],
  //!TODO Video Games
  [
    'Video Games',
    'assets/video_game.json',
    '20',
    'assets/images/video_game/Bioshock.png',
  ],
  //!TODO Tech - Q&A
  // [
  //   'Tech - Q&A',
  //   'assets/tech_QandA.json',
  //   '20',
  //   'assets/images/tech_QandA/xxx.png'),
  // ],
  [
    'Musical Instruments',
    'assets/musical_instruments.json',
    '20',
    'assets/images/musical_instruments/Flute.png',
  ],
  [
    'Dog Breeds',
    'assets/dog_breeds.json',
    '20',
    'assets/images/dog_breeds/Chow Chow.png',
  ],
  [
    'Game Characters',
    'assets/game_characters.json',
    '20',
    'assets/images/game_characters/Agent 47.png',
  ],
  //!TODO add movies txt
  // [
  //   'Movies',
  //   'assets/movies.json',
  //   '20',
  //   'assets/images/movies/Casino.png'),
  // ],
  [
    'Vegetables',
    'assets/vegetables.json',
    '20',
    'assets/images/vegetables/Broccoli.png',
  ],
  [
    'Nuts',
    'assets/nuts.json',
    '20',
    'assets/images/nuts/Acorn.png',
  ],
  [
    'Music Band',
    'assets/music_bands.json',
    '20',
    'assets/images/music_bands/ACDC.png',
  ],
  [
    'Mythical Creatures',
    'assets/mythical_creatures.json',
    '20',
    'assets/images/mythical_creatures/Fairy.png',
  ],
  [
    'Fashion Brands',
    'assets/fashion_brands.json',
    '20',
    'assets/images/fashion_brands/Adidas.png',
  ],
  [
    'Movie Villains',
    'assets/movie_villains.json',
    '20',
    'assets/images/movie_villains/Gollum.png',
  ],
  //!TODO add history Q&A
  // [
  //   'History - Q&A',
  //   'assets/history-QandA.json',
  //   '20',
  //   'assets/images/history-QandA/xxx.png'),
  // ],
  [
    'Superhero',
    'assets/superhero.json',
    '20',
    'assets/images/superhero/Batman.png',
  ],
  [
    'Sports',
    'assets/sports.json',
    '20',
    'assets/images/sports/Darts.png',
  ],
  [
    'Spices',
    'assets/spices.json',
    '20',
    'assets/images/spices/Ginger.png',
  ],
  [
    'Tech Companies',
    'assets/tech_companies.json',
    '20',
    'assets/images/tech_companies/Adobe.png',
  ],
  [
    'TV Shows',
    'assets/tv_shows.json',
    '20',
    'assets/images/tv_shows/Friends.png',
  ],
  [
    'Olympic Sports',
    'assets/olympic_sports.json',
    '20',
    'assets/images/olympic_sports/Karate.png',
  ],
  [
    'Supervillains',
    'assets/supervillains.json',
    '20',
    'assets/images/supervillains/Bane.png',
  ],
  [
    'Festivals',
    'assets/festivals.json',
    '20',
    'assets/images/festivals/Timkat.png',
  ],
  [
    'Extinct Animals',
    'assets/extinct_animals.json',
    '20',
    'assets/images/extinct_animals/Dodo.png',
  ],
  //!TODO add geography
  // [
  //   'Geography - Q&A',
  //   'assets/geography-QandA.json',
  //   '20',
  //   'assets/images/geography-QandA/Bane.png'),
  // ],
  [
    'Birds',
    'assets/birds.json',
    '20',
    'assets/images/birds/Emu.png',
  ],
  [
    'Guess the movie quotes',
    'assets/guess_the_movie.json',
    '20',
    'assets/images/guess_the_movie/Apollo 13.png',
  ],
  //!TODO add Historical Figures
  [
    'Historical Figures',
    'assets/historical_figures.json',
    '20',
    'assets/images/historical_figures/Mark Twain.png',
  ],
  [
    'Enterpreneurs and Founders',
    'assets/enterpreneurs_and_founders.json',
    '20',
    'assets/images/enterpreneurs_and_founders/Bill Gates.png',
  ],
  [
    'Board Games',
    'assets/board_games.json',
    '20',
    'assets/images/board_games/Chess.png',
  ],
  //!TODO add history Q&A
  // [
  //   'World Landamarks',
  //   'assets/world_landmarks.json',
  //   '20',
  //   'assets/images/world_landmarks/Colosseum.png'),
  // ],
  [
    'Nobel Peace Prize Winners',
    'assets/nobel_peace_prize_winners.json',
    '20',
    'assets/images/nobel_peace_prize_winners/Mother Teresa.png',
  ],
  [
    'Paintings',
    'assets/paintings.json',
    '20',
    'assets/images/paintings/The Kiss.png',
  ],
  [
    'Bridges',
    'assets/bridges.json',
    '20',
    'assets/images/bridges/Brooklyn.png',
  ],
  //!TODO add history Q&A
  // [
  //   'Science - Q&A',
  //   'assets/science-QandA.json',
  //   '20',
  //   'assets/images/science-QandA/xxx.png'),
  // ],
];
